### ISSUE TITLE
how can i make my on distro based on glaucus

### ISSUE THREAD

**Issue by alavaelian** [glaucuslinux/screenshots#3]
i want make a distros based on glacusus becose is very lightweight how i can make a distro with a navigator awesome wm alsa and most utils for a good distro

**Comment by firasuke** [comment]
Thanks for your interest in glaucus!

glaucus is unfortunately not yet available for use in production. You can however fork it and tamper with it to your liking.

I'd recommend taking a look at [mussel](https://github.com/firasuke/mussel) which is a cross-compilation toolchain that can be used to build and bootstrap your custom distribution from scratch, provided that you have enough expertise.

I also recommend that you check out the [awesome projects](https://github.com/firasuke/awesome) that I drew inspiration from while working on glaucus.

Good luck with your endeavours!
